services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: bacpebune
      MYSQL_USER: bacuser
      MYSQL_PASSWORD: bacpass
    volumes:
      - ./Data/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "server=mysql;port=3306;database=bacpebune;user=bacuser;password=bacpass;"
    depends_on:
      - mysql

volumes:
  mysql-data:
